# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

on:
  pull_request_target:
    paths:
      - Gemfile.lock
    types: [ready_for_review]
name: Add Dependency Owners
jobs:
  check:
    name: Check for dependency update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: refs/pull/${{ github.event.number }}/merge
          fetch-depth: 0
      - uses: actions/checkout@v2
        with:
          repository: 1debit/dependency_owners
          token: ${{ secrets.MERGEBOT_GITHUB_TOKEN }}
          path: ./.github/actions
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2
          bundler-cache: true
          working-directory: ./.github/actions
      - uses: ./.github/actions
        name: Add Dependency Owners
        with:
          token: ${{ secrets.MERGEBOT_GITHUB_TOKEN }}
        env:
          BUNDLE_GEMFILE: ./.github/actions/Gemfile
