# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

on:
  pull_request:
    paths:
      - 'Gemfile.lock'
name: Add Dependency Owners
jobs:
  check:
    name: Check for dependency update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # need to include base branch to make comparison
      # uses a hack/workaround to allow running shared action from private repo, via local checkout see:
      #  https://github.community/t/github-action-action-in-private-repository/16063
      - uses: actions/checkout@v2
        with:
          repository: 1debit/dependency_owners
          token: ${{ secrets.MERGEBOT_GITHUB_TOKEN }}
          path: .github/actions
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2
          bundler-cache: true
      - uses: ./.github/actions/dependency_owners
        with:
          dependency: 1debit/chime-atlas
